### PR TITLE
Fix unit tests and PHP8.1+ compatability

### LINKED ISSUE #113: Please fix compatibility with PHP 8.1
I am getting the following warnings from PHP 8.1:

```PHP
[23-Jan-2023 02:57:30 UTC] PHP Deprecated:  Rollbar\Payload\Level implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in .../wp-content/plugins/rollbar/vendor/rollbar/rollbar/src/Payload/Level.php on line 5
[23-Jan-2023 02:57:30 UTC] PHP Deprecated:  Rollbar\Payload\Frame implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in .../wp-content/plugins/rollbar/vendor/rollbar/rollbar/src/Payload/Frame.php on line 3
[23-Jan-2023 02:57:30 UTC] PHP Deprecated:  Rollbar\Payload\Context implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in .../wp-content/plugins/rollbar/vendor/rollbar/rollbar/src/Payload/Context.php on line 3
[23-Jan-2023 02:57:30 UTC] PHP Deprecated:  Rollbar\Payload\ExceptionInfo implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in .../wp-content/plugins/rollbar/vendor/rollbar/rollbar/src/Payload/ExceptionInfo.php on line 3
[23-Jan-2023 02:57:30 UTC] PHP Deprecated:  Rollbar\Payload\Trace implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in .../wp-content/plugins/rollbar/vendor/rollbar/rollbar/src/Payload/Trace.php on line 3
[23-Jan-2023 02:57:30 UTC] PHP Deprecated:  Rollbar\Payload\Body implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in .../wp-content/plugins/rollbar/vendor/rollbar/rollbar/src/Payload/Body.php on line 3
[23-Jan-2023 02:57:30 UTC] PHP Deprecated:  Rollbar\Payload\Data implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in .../wp-content/plugins/rollbar/vendor/rollbar/rollbar/src/Payload/Data.php on line 5
[23-Jan-2023 02:57:30 UTC] PHP Deprecated:  Rollbar\Payload\Request implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in .../wp-content/plugins/rollbar/vendor/rollbar/rollbar/src/Payload/Request.php on line 3
[23-Jan-2023 02:57:30 UTC] PHP Deprecated:  Rollbar\Payload\Server implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in .../wp-content/plugins/rollbar/vendor/rollbar/rollbar/src/Payload/Server.php on line 3
[23-Jan-2023 02:57:30 UTC] PHP Deprecated:  Rollbar\Payload\Payload implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in .../wp-content/plugins/rollbar/vendor/rollbar/rollbar/src/Payload/Payload.php on line 6
```

### PR DESCRIPTION
**Pull request by aaronjorbin**
## Description of the change

Fix #113 and #102

This updates the unit tests to use the [Yoast Pollyfill](https://github.com/Yoast/PHPUnit-Polyfills) and also [wp-env](https://www.npmjs.com/package/@wordpress/env) for testing across multiple versions of PHP. 

The underlying [rollbar-php](https://github.com/rollbar/rollbar-php) is both updated and kept the same. It's updated for sites running PHP8+, but kept the same for PHP7.  This introduces a bit of technical debt as the actual dependencies aren't in the composer file but instead are in the `php7` and `php8` folder. To help manage that, a script is included for updating those dependencies. 

There are a few spots in the code that now also include PHP version specific code. When php7 support is dropped, these will need to be cleaned up. 

Additionally, github actions are added in order to allow unit tests to run across multiple versions of PHP

## Testing Instructions

If you want to test this change manually, you can use wp-env. clone the repo and make sure git, docker, and node are installed on your machine.  Then run 

`npm install`
`WP_ENV_PHP_VERSION="7.0" npm run wp-env start -- --update` to start with PHP 7.0

You can login to Wordpress at http://localhost:8888/ with the username `admin` and the password `password`

If you want to test a different version of PHP, you can restart the env with a different PHP version passed in.  For example, `WP_ENV_PHP_VERSION="8.2" npm run wp-env start -- --update` to start with PHP 8.2

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Maintenance
- [ ] New release

### Development

- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review

- [x] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers assigned
- [ ] Issue from task tracker has a link to this pull request
- [ ] Changes have been reviewed by at least one other engineer

### CODE REVIEW

**Comment by aaronjorbin** [comment]
You can see the passing unit tests at https://github.com/aaronjorbin/rollbar-php-wordpress/actions/runs/5512267190

**Comment by aaronjorbin** [comment]
The 2,021 files changed is due to 
1) Moving from having the dependencies in the main composer.json file to there being separate php8 and php7 versions
2) Removing the dependencies that are actually dev dependencies from the build. 

The actual files changed that should be reviewed are and a quick summary for each file:
- [.github/workflows/php_unit.yml](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-9565dbbeb1d6d247ad28aa8780275b3fa2acf561bda7ae0da4c88eb64809a43c) - New action for the unit tests
- [.gitignore](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947) 
- [.wp-env.json](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-9fd21b09a0144355cfd001e3952767df08b2e04241994470aa1d627f797b171e) - New file for local env
- [readme.md](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) - Updated instructions for automated tests
- [bin/install-wp-tests.sh](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-96109e4cdb086501c1c7dae444c0c80fbbc59232a0412a2c331f7dcd995e117f) - deleted due to changes to how the tests are run now
- [bin/update-composer-dependencies](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-2edb4aaaff9b984872d64af68722c710d86201b81117c21f34485c8cb7f37121) - new script to make it easier to update dependencies
- [composer.json](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34) - Changed from including dependencies to having them in php7 and php8 versions, also updated test running and modified the dev dependencies so tests can run across multiple versions
- [package.json](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
- [php7/composer.json](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-98c4fb6daa32ca055d95e8195d83d07521d8514999ba4a718ef6399621db094a)
- [php8/composer.json](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-33c8d3d4b117d530592d93c7734bbe68fa2ab2ad0dd3b7925eba7603a90b4629)
- [phpunit.xml.dist](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-e35810879ec42bdd81797b3ccb72f6de28a8b4a0e3bfdba43183e133e866b892) - Ignore files without tests since this triggers an error in newer PHPUnit versions
- [rollbar-php-wordpress.php](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-f5628675fea57e890301560d68be736625fbd9b278745757539d81e520675bff) - Load autoloader based on PHP version
- [src/Plugin.php](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-c346b1aeac8259782c74702eadfe1d7a240ee3ecea6020ad2addede93c635cab) - handle differences in underlying library based on PHP version
- [src/Settings.php](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-eb1710f64250974d6d1550d421a31054e6079592ae3a8428cd9530bc086bdd94) - Handle differences in underlying library
- [tests/BaseTestCase.php](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-8c59e90b325df02fbdd2c2adb75cd97e7e739589ca0eb65a7611ed44538f3e87) - Use the [Yoast PHPUnit polyfill](https://github.com/Yoast/PHPUnit-Polyfills) library
- [tests/DefaultTest](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-5df5af1e5354616f536f2261b4cecc8e34c8144d48ce5d7838890a4f62bcab41) - use snakecase from https://github.com/Yoast/PHPUnit-Polyfills#testcases 
- [tests/PluginTest](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-cefb49fe1a83f71a2da400bfef0d7659ac3d679c46261fce56af2ee74e669b1f) - handle underlying library changes, snakecase due to https://github.com/Yoast/PHPUnit-Polyfills#testcases and also make dataProvidor static due to PHPUnit changes
- [tests/SettingsTest.php](https://github.com/rollbar/rollbar-php-wordpress/pull/114/files#diff-33d43d6b0690a15a6bd46a0db8cf43bb1a3da6c6b2c6626e80ccd28e1d0368b9)  snakecase due to https://github.com/Yoast/PHPUnit-Polyfills#testcases and also make dataProvidor static due to PHPUnit changes

**Comment by danielmorell** [comment]
Hi @aaronjorbin, thank you for the massive amount of work you have put into this! It will take me a little bit to review this, but I think this is heading in a good direction.

**Review by danielmorell — APPROVED** [review]
@aaronjorbin Thank you for the work you have put into this. It looks really good! Sorry it took me a bit to go through.

**Pull request merged**
