### PR TITLE
don’t start a session for wp-cron

### LINKED ISSUE #82: Rollbar plugin creating errors and reporting itself (cron)
Issue was brought up on Wordpress plugin page forum: https://wordpress.org/support/topic/rollbar-plugin-creating-errors-and-reporting-itself-cron/

```
Request url /wp-cron.php?doing_wp_cron=1554191111.1389780044555664062500

File /wp-content/plugins/rollbar/src/Settings.php line 103 in session_start

Issue is this line
if( !session_id()) {

Fixed by this change
if( !session_id() && !defined( 'DOING_CRON' )) {
```

### PR DESCRIPTION
**Pull request by andrewminion-luminfire**
Possible fix for #85 and #86
Fixes #82

### CODE REVIEW

**Comment by andrewminion-luminfire** [comment]
@ArturMoczulski Any plans to pull this in soon?

**Comment by ArturMoczulski** [comment]
@andrewminion-luminfire yes. I'm hoping to give the plugin a lot of love in the upcoming weeks. You can expect to be released soon

**Comment by Lalee10** [comment]
@ArturMoczulski in our codebase we have version 2.6.1 for this plugin but this change is not there. I see that last version release was on 28 Dec, 2019 but this PR was merge after that. I don't know how releases work but shouldn't the plugin version be updated so that everyone using the plugin can get these updates?

**Comment by fliespl** [comment]
@ArturMoczulski I still feel it's better to not use sessions when not needed (as in this case ). admin_notice would be enough here.

It's not only starting sessions causing error on cron - it would also break caching for frontend part (PHPSESS cookie might kill caching mechanism) of the page since it's hooked to "init". 

And as far as I remember rollbar-php sdk doesn't require sessions to work.

**Pull request merged**
