### PR TITLE
Also use the WP_ENV constant

### LINKED ISSUE #68: WP_ENV is not used
From Wordpress support forums:

```
I have WP_ENV specified in wp-config:
define( ‘WP_ENV’, ‘development’ );

But it doesn’t appear on the settings page: http://take.ms/sGd8U

Also, in email notifications:
Environment:	unknown
```
https://wordpress.org/support/topic/wp_env-is-not-used/

### PR DESCRIPTION
**Pull request by Brugman**
Hiya. I'm a new customer. You've got a few PRs incoming based on my first impressions. If these are welcome I'd love to write more.

## Description of the change

In my experience WP_ENV is more often used as a constant than an environment variable. I don't want to get rid of the environment variable, but if it doesn't exist can we check the constant?

Fixes #68

## Type of change

- New feature (non-breaking change that adds functionality)

## Related issues

None.

## Checklists

I'm not yet familiar with testing, I did test manually of course, and I'm on Windows. I hope you'll take this without testing, or can run tests on my behalf.

### CODE REVIEW

**Comment by Brugman** [comment]
There's a bunch of duplicate code in this PR. I couldn't find any example of reusable code in the plugin that I could mimic so I did it like this on purpose. Feel free to modify it.

**Review by danielmorell — CHANGES_REQUESTED** [review]
You could probably make `Plugin::getEnv()` a public static function that is called by both `Defaults::environment()` and `UI::environmentSettingNote()`. This would keep us from introducing bugs later by changing only one instance of our `WP_ENV` lookup.

**Comment by Brugman** [comment]
A public static function it will be.

Renamed the method to `getEnvironment()` to avoid confusion/conflict with PHP's native `getenv()`.

Manually tested, all 3 locations work well.

**Review by danielmorell — APPROVED** [review]
Looks good. Thank you!

**Pull request merged**
